apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-17T09:51:03Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "7465"
  uid: 6444426d-846c-42b8-8826-138cf106f109
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.103.240.225
  clusterIPs:
  - 10.103.240.225
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32442
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
